/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AssignProjectsJNI */

#ifndef _Included_AssignProjectsJNI
#define _Included_AssignProjectsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AssignProjectsJNI
 * Method:    assignProjects
 * Signature: (ILjava/util/ArrayList;Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_AssignProjectsJNI_assignProjects
  (JNIEnv *, jclass, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
